# Write the static inst/CITATION (design.md section 9) from the same fields
# qes_cite() uses (.qes_citation_fields in R/cite.R).
#
# Usage (from the package root): Rscript data-raw/make_citation.R
#
# inst/CITATION must not call package code: readCitationFile() can evaluate
# it without the namespace loaded. The version comes from `meta$Version`.
# tests/testthat/test-contract-exports.R checks that citation("qesR") equals
# qes_cite(NULL, style = "bibentry").

pkgload::load_all(".", quiet = TRUE)
f <- .qes_citation_fields
q <- function(x) paste0("\"", gsub("\"", "\\\\\"", x), "\"")

lines <- c(
  "# Generated by data-raw/make_citation.R from R/cite.R: do not edit by hand.",
  "bibentry(",
  "  bibtype = \"Manual\",",
  sprintf("  key = %s,", q(f$key)),
  sprintf("  title = %s,", q(f$title)),
  sprintf("  author = person(%s, %s),", q(f$given), q(f$family)),
  sprintf("  year = %s,", q(f$year)),
  "  note = paste(\"R package version\", meta$Version),",
  sprintf("  url = %s", q(f$url)),
  ")"
)
con <- file(file.path("inst", "CITATION"), open = "wb")
writeBin(charToRaw(paste0(paste(lines, collapse = "\n"), "\n")), con)
close(con)
cat("Wrote inst/CITATION\n")
