#!/usr/bin/env Rscript

# The coverage grids of README.md (design.md section 9; slices W.1 and W.2).
#
# README.md has one grid in its English section and one in its French
# section, each between the lines
#   <!-- coverage: start (generated by data-raw/readme_coverage.R) -->
#   <!-- coverage: end -->
# This script writes the grid of the shipped spec (.spec_readme_md(),
# R/hz-views.R) between every such pair. The website's home page has no
# grid: it links to the coverage page, generated when the site is built.
# data-raw/spec_check.R (V-P3) fails when a file is not current. Run it
# from the package root after any change to the spec:
#   Rscript data-raw/readme_coverage.R

# The files that carry the grid, and the reference page their target names
# link to (NULL: no links).
coverage_files <- list(
  list(path = "README.md", reference = NULL)
)

pkgload::load_all(".", quiet = TRUE, export_all = TRUE)

readme_coverage <- function(lines, grid) {
  start <- grep("^<!-- coverage: start", lines)
  end <- grep("^<!-- coverage: end", lines)
  if (length(start) == 0L || length(start) != length(end) || any(end <= start)) {
    stop("the coverage markers are missing or unpaired", call. = FALSE)
  }
  grid <- c("", strsplit(sub("\n$", "", grid), "\n", fixed = TRUE)[[1]], "")
  out <- lines[seq_len(start[1])]
  for (k in seq_along(start)) {
    upto <- if (k < length(start)) start[k + 1L] else length(lines)
    out <- c(out, grid, lines[end[k]:upto])
  }
  out
}

if (sys.nframe() == 0L) {
  for (f in coverage_files) {
    lines <- enc2utf8(readLines(f$path, encoding = "UTF-8", warn = FALSE))
    new <- readme_coverage(lines, .spec_readme_md(reference = f$reference))
    if (identical(new, lines)) {
      cat(sprintf("%s: the coverage grid is current.\n", f$path))
    } else {
      con <- file(f$path, open = "wb")
      writeBin(charToRaw(paste0(paste(new, collapse = "\n"), "\n")), con)
      close(con)
      cat(sprintf("%s: coverage grid written.\n", f$path))
    }
  }
}
